//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodaDestek.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VodaDestekEntities3 : DbContext
    {
        public VodaDestekEntities3()
            : base("name=VodaDestekEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TbRight> TbRight { get; set; }
        public virtual DbSet<TbTicket> TbTicket { get; set; }
        public virtual DbSet<TbUsers> TbUsers { get; set; }
        public virtual DbSet<TbUsersRight> TbUsersRight { get; set; }
    }
}
