//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodaDestek.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TbAdmin
    {
        public int InAdminId { get; set; }
        [Required(ErrorMessage = "Please Check Your  Username ")]
        public string StUserName { get; set; }
        [Required(ErrorMessage = "Please Check Your  Password ")]
        public string StPassword { get; set; }
        [Required(ErrorMessage = "Please Check Your Email ")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string StEmail { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DtDAte { get; set; }
    }
}
