//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodaDestek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbMail
    {
        public int InMailID { get; set; }
        public string StUserName { get; set; }
        public string StFullName { get; set; }
        public string StEmail { get; set; }
        public Nullable<int> InPhone { get; set; }
        public string StMessage { get; set; }
    }
}
