//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodaDestek.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TbTicket
    {
        public int InUserID { get; set; }

        [Required(ErrorMessage = "Please Check Your  Ticketname ")]
        public string StTicketName { get; set; }

        [Required(ErrorMessage = "Please Check Your  Surname ")]
        public string StSurname { get; set; }

        [Required(ErrorMessage = "Please Check Your Email ")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string StEmail { get; set; }

        [Required(ErrorMessage = "Please Check Your  Proje ")]
        public string StProje { get; set; }

        [Required(ErrorMessage = "Please Check Your  Subject ")]
        public string StSubject { get; set; }

        [Required(ErrorMessage = "Please Check Your  Title ")]
        public string StTitle { get; set; }

        [Required(ErrorMessage = "Please Check Your  Message ")]
        [MaxLength(50, ErrorMessage = "Message cannot be longer than 50 characters.")]
        public string StMessage { get; set; }
        public string StFile { get; set; }

        [Required(ErrorMessage = "Please Check Your  Date ")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DtDate { get; set; }
    }
}
