//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodaDestek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbUsersRight
    {
        public int InUserRightId { get; set; }
        public Nullable<int> InUserID { get; set; }
        public Nullable<int> InRightID { get; set; }
    
        public virtual TbRight TbRight { get; set; }
        public virtual TbUsers TbUsers { get; set; }
    }
}
